version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:14.10
commands:
  install_deps:
    description: "install dependencies"
    parameters:
      environment:
        type: string
        default: production
    steps:
      - run:
          command: |
             cd VAMobile
             yarn install --frozen-lockfile --non-interactive
             echo env:<<parameters.environment>>
             yarn env:<<parameters.environment>>
  lint:
    description: "Run lint"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn lint:ci
          when: always
  jest:
    description: "Run jest"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn test -w 1
          when: always
      - store_test_results:
          path: VAMobile/coverage/junit/
  create_keys_directory:
    description: "create directory for google keys"
    steps:
      - run:
          command: mkdir VAMobile/android/keys
  decode_keystore:
    description: "Decode the Play Store keystore"
    steps:
      - run:
          command: echo $GOOGLE_KS | base64 -di | tee keystore.jks VAMobile/android/keys/vamobile >/dev/null
  decode_android_service_account_json:
    description: "Decode service account file for fastlane Google supply functions"
    steps:
      - run:
          command: echo $GOOGLE_SA_JSON | base64 -di | tee keystore.jks VAMobile/android/keys/service-account.json >/dev/null
  bundle_ios:
    description: "Bundles RN code for iOS Build"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn bundle:ios
  bundle_android:
    description: "Bundles RN code for Android Build"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn bundle:android
  androind_internal:
    steps:
      - run:
          command: |
              cd VAMobile/android
              bundle exec fastlane internal version:daily
  set_staging_key:
    description: "Sets the app client secret env to the staging key"
    steps:
      - run:
          command: APP_CLIENT_SECRET=$APP_CLIENT_SECRET_STAGING
jobs:
  test:
    executor: default
    steps:
      - checkout
      - install_deps
      - lint
      - jest
  run:
    executor: default
    steps:
      - run: echo "run"
  build_and_deploy_android_test:
    executor: default
    steps:
      - checkout
      - install_deps:
          environment: staging
      - create_keys_directory
      - decode_keystore
      - decode_android_service_account_json
#      - lint
#      - jest
#      - bundle_android
      - run: cd VAMobile/android
      - restore_cache:
          key: 1-gems-{{ checksum "VAMobile/android/Gemfile.lock" }}
      - run: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "VAMobile/android/Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec fastlane internal version:daily
workflows:
  pr:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
      - run:
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
  build_android_test:
    jobs:
      - build_and_deploy_android_test:
          filters:
            tags:
              only: /^test_circle/
            branches:
              ignore: /.*/
