version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:14.10
commands:
  install_deps:
    description: "install dependencies"
    steps:
      - run:
          command: |
             cd VAMobile
             yarn install --frozen-lockfile --non-interactive
  lint:
    description: "Run lint"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn lint:ci
          when: always
  jest:
    description: "Run jest"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn test -w 1
          when: always
      - store_test_results:
          path: VAMobile/coverage/junit/
  decode_keystore:
    description: "Decode the Play Store keystore"
    steps:
      - run:
          command: echo $GOOGLE_KS | base64 -di | tee keystore.jks VAMobile/android/keys/vamobile >/dev/null
  decode_android_service_account_json:
    description: "Decode service account file for fastlane Google supply functions"
    steps:
      - run:
          command: echo $GOOGLE_SA_JSON | base64 -di | tee keystore.jks VAMobile/android/keys/service-account.json >/dev/null
  bundle_ios:
    description: "Bundles RN code for iOS Build"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn bundle:ios
  bundle_android:
    description: "Bundles RN code for Android Build"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn bundle:android
  androind_internal:
    steps:
      - run:
          command: |
              cd VAMobile/android
              fastlane internal version:daily

jobs:
  test:
    executor: default
    steps:
      - checkout
      - install_deps
      - lint
      - jest
  run:
    executor: default
    steps:
      - run: echo "run"
  build_and_deploy_android_test:
    executor: default
    steps:
      - checkout
      - install_deps
      - lint
      - jest
      - decode_keystore
      - decode_android_service_account_json
      - bundle_android
      - androind_internal
workflows:
  build_android_test:
    jobs:
      - build_and_deploy_android_test:
          filters:
            tags:
              only: /test_circle/

