version: 2.1
 
# Fake circleci config to prevent errors on gh-pages branch
jobs:
  fake-job:
    docker:
      - image: cimg/ruby:3.0.2-node
    steps:
      - run: echo "fake gh-pages job"
    filter:
      branches:
        ignore: gh-pages
