version: 2.1
executors:
  default:
    docker:
      - image: cimg/ruby:2.4.10-node
  android:
    docker:
      - image: circleci/android:api-30-node
    resource_class: large
  ios:
    macos:
      xcode: 12.3.0
commands:
  github_ssh_keys:
    description: "Use write keys for Git Hub"
    steps:
      - add_ssh_keys:
          fingerprints:
            - 71:99:d1:8a:19:c3:ed:06:45:be:cc:14:30:a7:ed:3d
  install_deps:
    description: "Install dependencies"
    parameters:
      environment:
        type: string
        default: staging
    steps:
      - run:
          command: |
            echo INSTALLING YARN
            npm install yarn
            cd VAMobile
            echo INSTALLING NODE MODULES
            yarn install --frozen-lockfile --non-interactive
            echo CREATING ENV FILE FOR env:<<parameters.environment>>
            yarn env:<<parameters.environment>>
  lint:
    description: "Run lint"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn lint:ci
          when: always
  jest:
    description: "Run jest"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn test -w 1
          when: always
      - store_test_results:
          path: VAMobile/coverage/junit/
  create_keys_directory:
    description: "create directory for google keys"
    steps:
      - run:
          command: mkdir VAMobile/android/keys
  decode_keystore:
    description: "Decode the Play Store keystore"
    steps:
      - run:
          command: echo $GOOGLE_KS | base64 -di | tee VAMobile/android/keys/vamobile >/dev/null
  decode_android_service_account_json:
    description: "Decode service account file for fastlane Google supply functions"
    steps:
      - run:
          command: echo $GOOGLE_SA_JSON | base64 -di | tee VAMobile/android/keys/service-account.json >/dev/null
  decode_local_properties:
    description: "Decode the local.properties file for Android"
    steps:
      - run:
          command: echo $ANDROID_LOCAL_PROPERTIES | base64 -di | tee VAMobile/android/local.properties >/dev/null
  bundle_ios:
    description: "Bundles RN code for iOS Build"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn bundle:ios
  bundle_android:
    description: "Bundles RN code for Android Build"
    steps:
      - run:
          command: |
              cd VAMobile
              yarn bundle:android
  android_fastlane:
    description: "Builds and deploys for Android to the specified lane and version"
    parameters:
      lane:
        type: string
        default: internal
      version:
        type: string
        default: daily
    steps:
      - github_ssh_keys
      - bundle_android
      - run: gem install bundler
      - run:
          command: cd VAMobile/android && bundle install --path vendor/bundle
      - save_cache:
          key: 1-gems-{{ checksum "VAMobile/android/Gemfile.lock" }}
          paths:
            - VAMobile/android/vendor/bundle
      - run:
          working_directory: VAMobile/android
          command: bundle exec fastlane <<parameters.lane>> version:<<parameters.version>>
  ios_fastlane:
    description: "Builds and deploys for iOS to the specified lane and version"
    parameters:
      version:
        type: string
        default: daily
      lane:
        type: string
        default: internal
    steps:
      - github_ssh_keys
      - bundle_ios
  set_staging_key:
    description: "Sets the app client secret env to the staging key"
    steps:
      - run:
          command: APP_CLIENT_SECRET=$APP_CLIENT_SECRET_STAGING
jobs:
  test:
    executor: default
    steps:
      - checkout
      - install_deps:
          environment: test
      - lint
      - jest
  run:
    executor: default
    steps:
      - run: echo "run"
  build_and_deploy_android:
    parameters:
      environment:
        type: string
        default: staging
      version:
        type: string
        default: daily
      lane:
        type: string
        default: internal
    executor: android
    steps:
      - run: echo env=<<parameters.environment>>, version=<<parameters.version>>, lane=<<parameters.lane>>
      - checkout
      - install_deps:
          environment: <<parameters.environment>>
      - create_keys_directory
      - decode_keystore
      - decode_android_service_account_json
      - decode_local_properties
      - lint
      - jest
      - android_fastlane:
          lane: <<parameters.lane>>
          version: <<parameters.version>>

  build_and_deploy_test_flight:
    parameters:
      environment:
        type: string
        default: staging
      version:
        type: string
        default: daily
      lane:
        type: string
        default: internal
    executor: ios
    steps:
      - run: echo env=<<parameters.environment>>, version=<<parameters.version>>, lane=<<parameters.lane>>
      - checkout
      - install_deps:
          environment: <<parameters.environment>>
      - lint
      - jest



workflows:
  pr:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
      - run:
          requires:
            - test
          filters:
            tags:
              ignore: /.*/
#  build_daily:
#    jobs:
#      - build_and_deploy_android:
#          environment: staging
#          version: daily
#          lane: internal
#      - build_and_deploy_test_flight
#      - merge_changes
#    triggers:
#      - schedule:
#          cron: "0 0 * * *"
#          filters:
#            branches:
#              only: develop
  build_android_test:
    jobs:
      - build_and_deploy_android:
          environment: staging
          version: daily
          lane: internal
          filters:
            tags:
              only: /^test_circle/
            branches:
              ignore: /.*/
