name: 'Setup Environment'
description: 'Checks out VA Mobile codebase and installs dependencies'
inputs:
  environment:
    description: 'Environment to use (e.g. test, staging, production)'
    required: true
    default: 'staging'
  install_bundler:
    description: 'Specifies whether or not to install ruby bundler (needed for builds only)'
    required: true
    default: false
