name: 'Setup node and install depenencies'
description: 'Checks out VA Mobile codebase and installs dependencies'
defaults:
  run:
    working-directory: VAMobile

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
