name: 'Setup Node Env'
description: 'Sets up node environment and installs dependencies'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
        cache-dependency-path: 'VAMobile/yarn.lock'
    - run: yarn install --frozen-lockfile --non-interactive
      shell: bash
