name: Build iOS

on:
  workflow_call:
    inputs:
      environment:
        type: string
        default: staging
      lane:
        type: string
        default: qa
      notes:
        type: string
        default: ''
      tf_group:
        type: string
        default: ''
      version:
        type: string
        default: qa
      use_slack_thread:
        type: boolean
        default: true

defaults:
  run:
    working-directory: VAMobile

env:
  APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
  APP_CLIENT_SECRET_PROD: ${{ secrets.APP_CLIENT_SECRET_PROD }}
  DEMO_PASSWORD: ${{ secrets.DEMO_PASSWORD }}

jobs:
  Build:
    runs-on: macos-latest
    env:
      APPSTORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ISSUER_ID }}
      APPSTORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
      APPSTORE_CONNECT_FILEPATH: './AppStoreConnectKey.p8'
      IOS_PROJ_FILE: 'VAMobile.xcodeproj'
      IOS_SCHEME: 'VAMobileRelease'
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      # Sets up node with v16 and restores global cache so we don't have to re-download dependencies
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VA_MOBILE_ROBOT_GITHUB_SSH_KEY }}
      - name: Decode files
        working-directory: VAMobile/ios
        run: |
          echo "${{ secrets.APPSTORE_CONNECT_BASE64 }}" | base64 --decode > "$APPSTORE_CONNECT_FILEPATH"
          echo "${{ secrets.IOS_GS_PLIST_BASE64 }}" | base64 --decode > GoogleService-Info.plist
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '13.4.1'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        working-directory: VAMobile
        run: |
          yarn install --frozen-lockfile --non-interactive
          yarn env:${{ inputs.environment }}
          yarn bundle:ios
      - name: Run fastlane
        run: |
          cd ios
          pod install
          bundle config set --local path 'vendor/bundle' && bundle install          
          bundle update fastlane
          bundle exec fastlane ${{ inputs.lane }} version:"${{ inputs.version }}" notes:"${{ inputs.notes }}" tfGroup:"${{ inputs.tf_group }}" --verbose
      - name: Run tmate
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v2
