#
# Lint and Unit Test jobs that runs our lint:ci and test npm scripts
#

name: '[Code Quality] Code Checks'

on:
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'release/v**'

defaults:
  run:
    working-directory: VAMobile

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'VAMobile/.nvmrc'
          # cache: 'yarn'
          # cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint:ci
  test:
    runs-on: ubuntu-4-cores-latest
    strategy:
      matrix:
        chunk: [1, 2, 3, 4, 5] # Array of chunks we want to split the tests into
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'VAMobile/.nvmrc'
          # node-version: '16'
          # cache: 'yarn'
          # cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: yarn test
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: bash ${GITHUB_WORKSPACE}/.github/scripts/setupTestMatrix.sh ${{ matrix.chunk }} 5
