# Runs e2e Detox tests

name: 'Detox Tests'

on:
  push:
      branches:
        - '5278-detox-automation'

jobs:
  ios_build:
    name: ios Build
    uses: ./.github/workflows/build_ios.yml
    secrets: inherit
