# Runs e2e Detox tests

name: 'Detox Tests'

on:
  push:
      branches:
        - '5278-detox-automation'

jobs:
  ios_build:
    name: ios Build
    uses: ./.github/workflows/build_ios.yml
    secrets: inherit
  detox_test:
    runs-on: macos-latest-xl
    needs: ios_build
    steps:
      - name: 'Install detox-cli'
        run: yarn global add detox-cli
      - name: 'Install applesimutils'
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: 'Build detox'
        run: yarn e2e:ios-build
      - name: 'Run detox test'
        run: yarn e2e:ios-test