#
# Detox e2e tests in CI
#

name: '[e2e] iOS Detox Test Run'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        required: true
        default: staging
        type: choice
        options:
          - staging
          - production
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'release/v**'

defaults:
  run:
    working-directory: VAMobile/ios

env:
  # IAM staging app client secret
  APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
  # IAM production app client secret
  APP_CLIENT_SECRET_PROD: ${{ secrets.APP_CLIENT_SECRET_PROD }}
  # Password to enter demo mode from login screen
  DEMO_PASSWORD: ${{ secrets.DEMO_PASSWORD }}
  # App Store Connect Issuer ID

jobs:
  e2e:
    runs-on: macos-latest-xl
    env:
      # App Store Connect Issuer ID
      APPSTORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ISSUER_ID }}
      # App Store Connect Key Id
      APPSTORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
      # Path to write secret key to. Also used by fastlane
      APPSTORE_CONNECT_FILEPATH: './AppStoreConnectKey.p8'
      # Xcode project file name
      IOS_PROJ_FILE: 'VAMobile.xcodeproj'
      # Xcode scheme to build
      IOS_SCHEME: 'VAMobileRelease'
      # Fast lane patch password
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Setup ssh-agent with VA Mobile Automation ssh key for fastlane match
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VA_MOBILE_ROBOT_GITHUB_SSH_KEY }}
      - name: Decode base64 encoded App Store Connect API key and GoogleService-Info.plist
        run: |
          echo "Notes: e2e test run"
          echo "${{ secrets.APPSTORE_CONNECT_BASE64 }}" | base64 --decode > "$APPSTORE_CONNECT_FILEPATH"
          echo "${{ secrets.IOS_GS_PLIST_BASE64 }}" | base64 --decode > GoogleService-Info.plist
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Setup node and restore yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install macOS dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Install npm dependencies
        run: cd .. && yarn install --frozen-lockfile --non-interactive
      - name: PWD
        run: pwd
      - name: Install Detox
        run: cd .. && yarn global add detox-cli
      - name: Set app environment variables
        run: cd .. && yarn env:staging
      - name: Bundle app
        run: cd .. && yarn e2e:ios-build
      - name: Install pods
        run: pod install
      - name: Install gems
        run: bundle install
      - name: Run e2e tests
        run: cd .. && yarn e2e:ios-tes