# Feature builds that can be run on-demand by tagging a branch with the
# feature-build- prefix.  Will use the subsequent words in the tag as 
# release notes

name: Feature Build

on:
  push:
    tags:
      - 'feature-build-*'
    branches:
      - nr-4736-feature-build-workflow

defaults:
  run:
    working-directory: VAMobile

jobs:
  ios:
    name: iOS Feature Build
    uses: ./.github/workflows/build_ios.yml
    secrets: inherit
    with:
      lane: on_demand
  android:
    name: Android Feature Build
    uses: ./.github/workflows/build_android.yml
    secrets: inherit
    with:
      lane: on_demand

