#
# Lint job that run with each push and PR
#

name: Lint

on: [push, pull_request]

defaults:
  run:
    working-directory: VAMobile

jobs:
  skip_check:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'true'
          do_not_skip: '["workflow_dispatch", "schedule"]'
  lint:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    name: eslint && tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Sets up node with v16 and restores global cache so we don't have to re-download dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint:ci
