name: Lint and Test

on: [push, pull_request]

defaults:
  run:
    working-directory: VAMobile

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint:ci
  test:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      matrix:
        chunk: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: yarn test
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/setupTestMatrix.sh ${{ matrix.chunk }} 5
