#
# Checks if QA approvals are necessary, and if so runs the associated action when a new review is added
#

name: '[Utils] QA required approval'

on:
  pull_request:
    types: [opened, edited, converted_to_draft, ready_for_review, reopened]
    paths:
      - 'VAMobile/src/**'
      - 'VAMobile/package.json'
      - '!VAMobile/src/**.test.*'

  pull_request_review:
    types: [submitted, dismissed]

  pull_request_target:
    branches:
      - 'develop'

jobs:
  check_for_qa_approval:
    name: Requires QA approval
    runs-on: ubuntu-latest
    steps:
      - name: Check QA approval
        shell: bash
        run: |
          approvals=$(curl --request GET \
          --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
          --header 'Authorization: ${{ secrets.GITHUB_TOKEN }}' \
          --header 'Content-Type: application/json' |
          jq '[map(select(.state == "APPROVED")) | .[] .user.login]')

          echo $approvals
          
          if $approvals | jq '(. | length) > 1'
            then
              if $approvals | jq '(. - (. - ("rbontrager","DJUltraTom","TKDickson")) | length)'
                then
                echo 'This PR has QA approval to merge'
              else 
                echo 'This PR requires QA approval to merge'
                exit 1
              fi
          else
            echo 'This PR requires 3 approvals, including one QA approval, before merging.'
            exit 1
          fi
