#
# Lint and Unit Test jobs that runs our lint:ci and test npm scripts
#

name: '[Code Quality] QA Approval'

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  approval:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Do the thing
        run: echo ${{ github.event.review }}