name: Daily QA Build

on:
  push:
    branches:
      - nr-4731-qa-workflow

defaults:
  run:
    working-directory: VAMobile

env:
  APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
  APP_CLIENT_SECRET_PROD: ${{ secrets.APP_CLIENT_SECRET_PROD }}
  DEMO_PASSWORD: ${{ secrets.DEMO_PASSWORD }}

jobs:
  # build_ios:
  #   runs-on: macos-latest
  #   env:
  #     APPSTORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ISSUER_ID }}
  #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  #     APPSTORE_CONNECT_API_KEY_ID: ${{ secrets.APPSTORE_CONNECT_API_KEY_ID }}
  #     APPSTORE_CONNECT_BASE64: ${{ secrets.APPSTORE_CONNECT_BASE64 }}
  #     IOS_GS_PLIST_BASE64: ${{ secrets.IOS_GS_PLIST_BASE64 }}
  #     APPSTORE_CONNECT_FILEPATH: './AppStoreConnectKey.p8'
  #     IOS_PROJ_FILE: 'VAMobile.xcodeproj'
  #     IOS_SCHEME: 'VAMobileRelease'
  #   steps:
  #     - uses: actions/checkout@v3
  #     # Sets up node with v16 and restores global cache so we don't have to re-download dependencies
  #     - name: webfactory/ssh-agent
  #       uses: webfactory/ssh-agent@v0.7.0
  #       with:
  #         ssh-private-key: ${{ secrets.VA_MOBILE_ROBOT_GITHUB_SSH_KEY }}
  #     - name: Decode files
  #       working-directory: VAMobile/ios
  #       run: |
  #         echo "$APPSTORE_CONNECT_BASE64" | base64 --decode > "$APPSTORE_CONNECT_FILEPATH"
  #         echo "$IOS_GS_PLIST_BASE64" | base64 --decode > GoogleService-Info.plist
  #     - uses: maxim-lobanov/setup-xcode@v1
  #       with:
  #         xcode-version: '13.4.1'
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16'
  #         cache: 'yarn'
  #         cache-dependency-path: 'VAMobile/yarn.lock'
  #     - name: Install dependencies
  #       working-directory: VAMobile
  #       run: |
  #         yarn install --frozen-lockfile --non-interactive
  #         yarn env:staging
  #         yarn bundle:ios
  #         cd ios
  #         pod install
  #         bundle config set --local path 'vendor/bundle' && bundle install          
  #         bundle update fastlane
  #         bundle exec fastlane qa version:qa notes:"Narin GHA test" tfGroup:"Development Team" --verbose
  #     - name: Run tmate
  #       if: ${{ failure() }}
  #       uses: mxschmitt/action-tmate@v2

  build_android_qa:
    runs-on: ubuntu-latest
    env:
      ANDROID_KS_KEY_ALIAS: ${{ secrets.ANDROID_KS_KEY_ALIAS }}
      ANDROID_KS_KEY_PW: ${{ secrets.ANDROID_KS_KEY_PW }}
      ANDROID_KS_PW: ${{ secrets.ANDROID_KS_PW }}
      GOOGLE_KS: ${{ secrets.GOOGLE_KS }} # vamobile keystore base64 encoded
      GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
      FIREBASE_ANDROID_APP_ID: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
      FIREBASE_DIST_KEY_FILEPATH: ${{ secrets.FIREBASE_DIST_KEY_FILEPATH }}
    steps:
      - uses: actions/checkout@v3
      # Sets up node with v16 and restores global cache so we don't have to re-download dependencies
      - uses: ./.github/workflows/build_android.yml
        with:
          notes: 'Narin GHA Test'
      - name: Run tmate
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v2
