name: Daily QA Build

on:
  push:
    branches:
      - nr-4731-qa-workflow

defaults:
  run:
    working-directory: VAMobile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Sets up node with v16 and restores global cache so we don't have to re-download dependencies
      - name: Decode files
        env:
          ANDROID_KS_KEY_ALIAS: ${{ secrets.ANDROID_KS_KEY_ALIAS }}
          ANDROID_KS_KEY_PW: ${{ secrets.ANDROID_KS_KEY_PW }}
          ANDROID_KS_PW: ${{ secrets.ANDROID_KS_PW }}
          GOOGLE_VAMOBILE_KEYSTORE_BASE64: ${{ secrets.GOOGLE_VAMOBILE_KEYSTORE_BASE64 }}
          GOOGLE_SERVICE_ACCOUNT_JSON_BASE64: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_BASE64 }}
          GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
          FIREBASE_DIST_FILE_BASE64: ${{ secrets.FIREBASE_DIST_FILE_BASE64 }}
        run: |
          mkdir android/keys
          cd android/keys
          echo "$GOOGLE_VAMOBILE_KEYSTORE_BASE64" | base64 --decode > vamobile
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON_BASE64" | base64 --decode > service-account.json
          echo "$FIREBASE_DIST_FILE_BASE64" | base64 --decode > firebase-dist.json

          echo "GOOGLE_VAMOBILE_KEYSTORE_BASE64" >> secrets.txt
          echo "$GOOGLE_VAMOBILE_KEYSTORE_BASE64" >> secrets.txt
          echo "===" >> secrets.txt

          echo "GOOGLE_SERVICE_ACCOUNT_JSON_BASE64" >> secrets.txt
          echo "$GOOGLE_SERVICE_ACCOUNT_JSON_BASE64" >> secrets.txt
          echo "===" >> secrets.txt

          echo "FIREBASE_DIST_FILE_BASE64" >> secrets.txt
          echo "$FIREBASE_DIST_FILE_BASE64" >> secrets.txt
          echo "===" >> secrets.txt

          cd ..
          cd app
          echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > google-services.json

          echo "GOOGLE_SERVICES_JSON_BASE64" >> secrets.txt
          echo "$GOOGLE_SERVICES_JSON_BASE64" >> secrets.txt
          echo "===" >> secrets.txt


          echo "ANDROID_KS_KEY_ALIAS" >> secrets.txt
          echo $ANDROID_KS_KEY_ALIAS >> secrets.txt
          echo "===" >> secrets.txt


          echo "ANDROID_KS_KEY_PW" >> secrets.txt
          echo $ANDROID_KS_KEY_PW >> secrets.txt
          echo "===" >> secrets.txt

          echo "ANDROID_KS_PW" >> secrets.txt
          echo $ANDROID_KS_PW >> secrets.txt
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'
          # bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile --non-interactive
          yarn env:staging
          yarn bundle:android
          cd android
          bundle check || bundle config set --local path 'vendor/bundle' && bundle install
          bundle update fastlane
          bundle exec fastlane qa --verbose version:qa notes:"Narin GHA test" psTrack:""
      - name: Run tmate
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v2
