# Daily QA Build workflow that runs the reusable build_ios and build_android workflows
# with default inputs for QA builds

name: Daily QA Build

on:
  # Run on weekdays 4:00 AM UTC
  # schedule:
  #   - cron: '0 4 * * 1,2,3,4,5'
  push:
    branches:
      - feature/4737-Theo-SlackNotificationsGHA

defaults:
  run:
    working-directory: VAMobile

jobs:
  start_slack_thread:
    name: Start Slack thread
    uses: ./.github/workflows/start_slack_thread.yml
    secrets: inherit
    with:
      message: 'QA build process starting. Please see :thread: for results. This process may take a while.'
  set_slack_thread_ts:
    name: Set SLACK_THREAD_TS environment variable
    needs: start_slack_thread
    runs-on: ubuntu-latest
    steps:
      - run: echo 'SLACK_THREAD_TS=${{needs.start_slack_thread.outputs.thread_ts}}" >> $GITHUB_ENV
  # ios:
  #   name: iOS QA Build
  #   uses: ./.github/workflows/build_ios.yml
  #   secrets: inherit
  android:
    name: Android QA Build
    needs: start_slack_thread
    uses: ./.github/workflows/build_android.yml
    secrets: inherit
