name: Daily QA Build

on:
  push:
    branches:
      - nr-4731-qa-workflow
  # schedule:
  #   - cron: '30 3 * * 1,2,3,4,5' # Weekdays 3:30 AM UTC

defaults:
  run:
    working-directory: VAMobile

jobs:
  # ios:
  #   name: iOS QA Build
  #   uses: ./.github/workflows/build_ios.yml
  #   secrets: inherit
  android:
    name: Android QA Build
    uses: ./.github/workflows/build_android.yml
    secrets: inherit
    with:
      notes: 'Narin GHA Test'
