name: Start Slack Thread

on:
  workflow_call:
    inputs:
      message:
        type: string
        required: true
    outputs:
      thread_ts:
        value: ${{ jobs.start_thread.outputs.thread_ts }}

jobs:
  start_thread:
    runs-on: ubuntu-latest
    env:
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
    outputs:
      thread_ts: ${{ steps.start_thread.outputs.SLACK_THREAD_TS }}
    steps:
      - name: Start Slack thread
        id: start_thread
        run: |
          ts=$(curl -X POST -H 'Authorization: Bearer '"$SLACK_API_TOKEN"' ' \
              -H 'Content-type: application/json' \
              --data '{"channel":"'C022SV53ASZ'","text":"${{inputs.message}}"}' \
              https://slack.com/api/chat.postMessage|
              jq -r '.ts')
            echo SLACK_THREAD_TS=${ts} >> $GITHUB_OUTPUT
