#
# Unit test jobs that run with each push and PR
#

name: Unit Tests

on: [push, pull_request]

defaults:
  run:
    working-directory: VAMobile

jobs:
  skip_check:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'true'
          do_not_skip: '["workflow_dispatch", "schedule"]'
  test:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    name: yarn test
    strategy:
      matrix:
        chunk: [1, 2, 3, 4, 5] # Array of chunks we want to split the tests into
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: 'VAMobile/yarn.lock'
      - name: Install dependencies
        run: yarn install --frozen-lockfile --non-interactive
      - name: yarn test
        # GHA does not have test splitting built in, so we run this script to split our tests into chunks and run
        # jest with the specified files.  The number at the end is the # of chunks we're splitting the tests into.
        # This should match the numbers of items in the matrix chunk array above
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/setupTestMatrix.sh ${{ matrix.chunk }} 5
