name: "Update Testrail Run"

on:
  repository_dispatch:
    types:
      - update_testrail_run

jobs:
  update_run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Received web hook"
      - run: echo ${{github.event}} | jq -r '.'
